### ISSUE TITLE
wrong answer in correction of the question on quantiles

### ISSUE THREAD

**Issue by drblobfish** [mahendra-mariadassou/learningr#4]
https://github.com/mahendra-mariadassou/learningr/blob/96756b3a830e0ab79c3046f8e61cc3138b855dff/inst/tutorials/02.1_random_variables/random_variables.Rmd#L684

The correction gives a false answer :

https://github.com/mahendra-mariadassou/learningr/blob/96756b3a830e0ab79c3046f8e61cc3138b855dff/inst/tutorials/02.1_random_variables/random_variables.Rmd#L688

**Comment by mahendra-mariadassou** [comment]
Indeed, thanks for noticing the typo.
